"""Scalable J=1 coarse-pair plus fine-label-unary certificate search.

This module is numerical exploration only.  It preserves every fine-label
upper constraint and every typed lower constraint.  High-order upper rows are
generated by an exact finite dynamic-programming oracle; no fine tuple is
sampled.  ``ok`` remains fail-closed behind an independent complete semantic
replay at the requested tolerance.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from fractions import Fraction
from hashlib import sha256
from itertools import combinations_with_replacement
import json
from math import comb, isfinite
from pathlib import Path
from time import perf_counter
from typing import Any, Mapping, Sequence

import numpy as np
from scipy.sparse import coo_matrix, csr_matrix, vstack

from .group_certificate import GroupPartition
from .joint_group_lp import _low_matrix
from .low_order import (
    LowOrderCGSpec,
    _anchor_keys,
    _context,
    _costs,
    _mirror_key,
    _pair_candidates,
    _scan,
    _summary,
    _valid_key,
)
from .persistent_joint_oracle import PersistentBackendError, PersistentBackendSpec, _load_highspy


SCHEMA_VERSION = "v016-fine-unary-large-numeric-v1"
ARITIES = (3, 4, 5)


def _canonical_sha(value: Any) -> str:
    return sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")
    ).hexdigest()


def _pair_index(left: np.ndarray | int, right: np.ndarray | int, groups: int):
    a = np.minimum(left, right)
    b = np.maximum(left, right)
    return a * groups - a * (a - 1) // 2 + b - a


@dataclass(frozen=True, slots=True)
class Envelope:
    """Non-dominated DP states for ``S + z P``, with z in [0,1]."""

    products: np.ndarray
    sums: np.ndarray
    paths: np.ndarray


def _pareto_envelope(products: np.ndarray, sums: np.ndarray, paths: np.ndarray) -> Envelope:
    """Drop only states dominated for every future multiplier z in [0,1].

    If another state has both a no-smaller product and a no-smaller unary
    sum, the removed state can never maximize ``sum + z*product``.  This
    dominance rule is deliberately more conservative than floating convex-
    hull pruning and therefore cannot hide a fine-label witness.
    """

    p = np.asarray(products, dtype=np.float64).reshape(-1)
    s = np.asarray(sums, dtype=np.float64).reshape(-1)
    a = np.asarray(paths, dtype=np.int32)
    if (
        p.shape != s.shape
        or a.ndim != 2
        or a.shape[0] != len(p)
        or not len(p)
        or not np.all(np.isfinite(p))
        or not np.all(np.isfinite(s))
        or np.any(p < 0)
        or np.any(p > 1)
    ):
        raise ValueError("malformed envelope states")
    # Primary order: decreasing P.  Secondary: decreasing S.  A state is
    # retained exactly when its S is a new strict record.
    order = np.lexsort((-s, -p))
    ordered_s = s[order]
    prior = np.maximum.accumulate(ordered_s)
    keep = np.ones(len(order), dtype=bool)
    if len(order) > 1:
        keep[1:] = ordered_s[1:] > prior[:-1]
    selected = order[keep]
    # Sort by increasing P and retain the exact upper convex chain.  A point
    # below a chord cannot maximize S+zP for any z.  Fast floating signs are
    # accepted only outside a conservative rounding-error interval; ambiguous
    # orientations fall back to exact rational arithmetic on the input binary
    # floats.  Thus hull pruning is an exact optimization, not a heuristic.
    selected = selected[np.argsort(p[selected], kind="stable")]
    stack: list[int] = []

    def slope_left_le_right(i: int, j: int, k: int) -> bool:
        pi, pj, pk = map(float, (p[i], p[j], p[k]))
        si, sj, sk = map(float, (s[i], s[j], s[k]))
        left = (sj - si) * (pk - pj)
        right = (sk - sj) * (pj - pi)
        determinant = left - right
        error = 64.0 * np.finfo(np.float64).eps * (
            abs(left) + abs(right) + np.finfo(np.float64).tiny
        )
        if determinant < -error:
            return True
        if determinant > error:
            return False
        fi, fj, fk = (Fraction.from_float(value) for value in (pi, pj, pk))
        yi, yj, yk = (Fraction.from_float(value) for value in (si, sj, sk))
        return (yj - yi) * (fk - fj) <= (yk - yj) * (fj - fi)

    for index in map(int, selected):
        while len(stack) >= 2 and slope_left_le_right(stack[-2], stack[-1], index):
            stack.pop()
        stack.append(index)
    hull = np.asarray(stack, dtype=np.int64)
    return Envelope(p[hull], s[hull], a[hull])


def _extend_envelope(
    frontier: Envelope,
    member_labels: np.ndarray,
    failures: np.ndarray,
    unary: np.ndarray,
) -> Envelope:
    labels = np.asarray(member_labels, dtype=np.int32).reshape(-1)
    if not len(labels):
        raise ValueError("every label group must be nonempty")
    if np.any(labels < 0) or np.any(labels >= len(failures)):
        raise ValueError("label group contains an invalid label")
    rows, count = len(frontier.products), len(labels)
    products = (frontier.products[:, None] * failures[labels][None, :]).reshape(-1)
    sums = (frontier.sums[:, None] + unary[labels][None, :]).reshape(-1)
    prefixes = np.repeat(frontier.paths, count, axis=0)
    appended = np.tile(labels, rows)[:, None]
    return _pareto_envelope(products, sums, np.column_stack((prefixes, appended)))


def _combine_envelopes(frontier: Envelope, one_label: Envelope) -> Envelope:
    """Extend a prefix by an already exact-pruned one-label envelope."""

    rows, count = len(frontier.products), len(one_label.products)
    products = (frontier.products[:, None] * one_label.products[None, :]).reshape(-1)
    sums = (frontier.sums[:, None] + one_label.sums[None, :]).reshape(-1)
    prefixes = np.repeat(frontier.paths, count, axis=0)
    appended = np.tile(one_label.paths, (rows, 1))
    return _pareto_envelope(products, sums, np.column_stack((prefixes, appended)))


def _maximize_terminal(
    frontier: Envelope,
    one_label: Envelope,
) -> tuple[float, tuple[int, ...], int]:
    """Price the final coordinate directly, without building an unused hull.

    After the last label there is no future multiplier ``z``.  The required
    value is therefore simply the maximum of ``S + r*P + u`` over every
    retained prefix state and every member of the final group.  Enumerating
    that complete Cartesian product is semantically identical to extending
    and pruning an envelope, while avoiding a sort, exact hull predicates and
    path copies for each terminal coarse multiset.
    """

    objective = (
        frontier.products[:, None] * one_label.products[None, :]
        + frontier.sums[:, None]
        + one_label.sums[None, :]
    )
    flat = int(np.argmax(objective))
    prefix_index, label_index = divmod(flat, len(one_label.products))
    path = tuple(
        sorted(
            (*map(int, frontier.paths[prefix_index]), int(one_label.paths[label_index, 0]))
        )
    )
    return float(objective[prefix_index, label_index]), path, int(objective.size)


def maximize_upper_tuple(
    group_tuple: Sequence[int],
    label_groups: Sequence[int],
    failures: Sequence[float],
    unary: Sequence[float],
) -> tuple[float, tuple[int, ...], int]:
    """Exactly maximize ``prod(failure)+sum(unary)`` for one group tuple.

    Exact here means exact over the supplied IEEE-754 values: the DP drops
    only coordinate-wise dominated states.  It never samples labels.
    """

    groups = tuple(int(value) for value in group_tuple)
    membership = np.asarray(label_groups, dtype=np.int32)
    r = np.asarray(failures, dtype=np.float64)
    u = np.asarray(unary, dtype=np.float64)
    if (
        not groups
        or membership.shape != r.shape
        or r.shape != u.shape
        or not np.all(np.isfinite(r))
        or not np.all(np.isfinite(u))
        or np.any(r < 0)
        or np.any(r > 1)
        or any(group < 0 or group > int(membership.max()) for group in groups)
    ):
        raise ValueError("invalid upper-tuple maximization input")
    frontier = Envelope(
        np.ones(1, dtype=np.float64),
        np.zeros(1, dtype=np.float64),
        np.empty((1, 0), dtype=np.int32),
    )
    for group in groups:
        frontier = _extend_envelope(frontier, np.flatnonzero(membership == group), r, u)
    values = frontier.products + frontier.sums
    index = int(np.argmax(values))
    path = tuple(sorted(map(int, frontier.paths[index])))
    return float(values[index]), path, int(len(frontier.products))


def brute_force_upper_tuple(
    group_tuple: Sequence[int],
    label_groups: Sequence[int],
    failures: Sequence[float],
    unary: Sequence[float],
) -> tuple[float, tuple[int, ...]]:
    """Test-only full Cartesian oracle for tiny label sets."""

    membership = np.asarray(label_groups, dtype=np.int32)
    r = np.asarray(failures, dtype=np.float64)
    u = np.asarray(unary, dtype=np.float64)
    pools = [tuple(map(int, np.flatnonzero(membership == int(group)))) for group in group_tuple]
    if any(not pool for pool in pools):
        raise ValueError("empty group in brute-force oracle")
    best_value = -np.inf
    best_path: tuple[int, ...] | None = None
    import itertools

    for path in itertools.product(*pools):
        value = float(np.prod(r[list(path)]) + np.sum(u[list(path)]))
        ordered = tuple(sorted(path))
        if value > best_value or (value == best_value and (best_path is None or ordered < best_path)):
            best_value, best_path = value, ordered
    assert best_path is not None
    return best_value, best_path


@dataclass(frozen=True, slots=True)
class FineUnaryLargeSettings:
    """Finite numerical-search budget; none of these weaken final coverage."""

    time_limit_sec: float = 75.0
    final_check_reserve_sec: float = 12.0
    max_rounds: int = 32
    max_low_rows: int = 150_000
    max_active_rows: int = 650_000
    max_group_multisets: int = 100_000
    max_csr_bytes: int = 768 * 1024**2
    add_low_rows_per_round: int = 8192
    add_upper_rows_per_round: int = 8192
    partners_per_label: int = 8
    seed_anchor_count: int = 2
    low_block_size: int = 128
    tolerance: float = 1e-9

    def __post_init__(self) -> None:
        for name in (
            "max_rounds",
            "max_low_rows",
            "max_active_rows",
            "max_group_multisets",
            "max_csr_bytes",
            "add_low_rows_per_round",
            "add_upper_rows_per_round",
            "partners_per_label",
            "low_block_size",
        ):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError(f"{name} must be a positive exact integer")
        if (
            isinstance(self.seed_anchor_count, bool)
            or not isinstance(self.seed_anchor_count, int)
            or self.seed_anchor_count < 0
        ):
            raise ValueError("seed_anchor_count must be a nonnegative exact integer")
        for name in ("time_limit_sec", "final_check_reserve_sec", "tolerance"):
            value = getattr(self, name)
            if isinstance(value, bool) or not isfinite(value) or value <= 0:
                raise ValueError(f"{name} must be finite and positive")
        if self.time_limit_sec >= 90 or self.final_check_reserve_sec >= self.time_limit_sec:
            raise ValueError("wall budget must stay below 90s and exceed final reserve")
        if not 1e-10 <= self.tolerance <= 1e-7:
            raise ValueError("tolerance must lie in [1e-10,1e-7]")


@dataclass(frozen=True, slots=True)
class FineUnaryLayout:
    rho: int
    lambda_start: int
    lambda_stop: int
    low_width: int
    groups: int
    pairs: int
    labels: int
    unary_blocks: Mapping[int, slice]
    t_blocks: Mapping[tuple[int, str], slice]
    k_blocks: Mapping[int, slice]
    width: int


@dataclass(frozen=True, slots=True)
class FineUnaryContext:
    low: Any
    partition: GroupPartition
    label_groups: np.ndarray
    members: tuple[np.ndarray, ...]
    weights: tuple[float, ...]
    failures: np.ndarray


def _fine_context(spec: Any, bucket_group_map: Sequence[int] | GroupPartition) -> FineUnaryContext:
    low = _context(spec)
    partition = (
        bucket_group_map
        if isinstance(bucket_group_map, GroupPartition)
        else GroupPartition(tuple(bucket_group_map))
    )
    if len(partition.bucket_groups) != low.buckets:
        raise ValueError("one coarse group is required per fine bucket")
    weights = tuple(float(value) for value in spec.weights)
    if len(weights) != 5 or any(not isfinite(value) or value < 0 for value in weights):
        raise ValueError("fine-unary solver requires five finite nonnegative weights")
    label_groups = np.asarray(partition.label_groups, dtype=np.int32)
    members = tuple(
        np.flatnonzero(label_groups == group).astype(np.int32)
        for group in range(partition.num_label_groups)
    )
    if any(not len(group) for group in members):
        raise ValueError("every coarse label group must be nonempty")
    return FineUnaryContext(
        low=low,
        partition=partition,
        label_groups=label_groups,
        members=members,
        weights=weights,
        failures=1.0 - low.q,
    )


def _layout(context: FineUnaryContext) -> FineUnaryLayout:
    labels = 2 * context.low.buckets
    groups = context.partition.num_label_groups
    pairs = comb(groups + 1, 2)
    low_width = 1 + 4 * context.low.buckets
    cursor = low_width
    unary_blocks: dict[int, slice] = {}
    for arity in ARITIES:
        unary_blocks[arity] = slice(cursor, cursor + labels)
        cursor += labels
    t_blocks: dict[tuple[int, str], slice] = {}
    for arity in ARITIES:
        for family in ("u", "a", "s"):
            t_blocks[(arity, family)] = slice(cursor, cursor + groups)
            cursor += groups
    k_blocks: dict[int, slice] = {}
    for arity in ARITIES:
        k_blocks[arity] = slice(cursor, cursor + pairs)
        cursor += pairs
    return FineUnaryLayout(
        rho=0,
        lambda_start=1,
        lambda_stop=low_width,
        low_width=low_width,
        groups=groups,
        pairs=pairs,
        labels=labels,
        unary_blocks=unary_blocks,
        t_blocks=t_blocks,
        k_blocks=k_blocks,
        width=cursor,
    )


def _multisets(groups: int, arity: int) -> np.ndarray:
    count = comb(groups + arity - 1, arity)
    return np.fromiter(
        (value for row in combinations_with_replacement(range(groups), arity) for value in row),
        dtype=np.int32,
        count=count * arity,
    ).reshape(count, arity)


def _sparse_block(
    width: int,
    rows: int,
    column_terms: Sequence[np.ndarray],
    value_terms: Sequence[np.ndarray | float],
) -> csr_matrix:
    if len(column_terms) != len(value_terms):
        raise AssertionError("column/value term count mismatch")
    row_index = np.concatenate([np.arange(rows, dtype=np.int32) for _ in column_terms])
    columns = np.concatenate(
        [np.asarray(value, dtype=np.int32).reshape(rows) for value in column_terms]
    )
    values = np.concatenate(
        [
            np.full(rows, value, dtype=np.float64)
            if np.isscalar(value)
            else np.asarray(value, dtype=np.float64).reshape(rows)
            for value in value_terms
        ]
    )
    result = coo_matrix((values, (row_index, columns)), shape=(rows, width)).tocsr()
    result.sum_duplicates()
    result.eliminate_zeros()
    result.sort_indices()
    return result


def _pair_columns(combos: np.ndarray, start: int, groups: int) -> list[np.ndarray]:
    arity = combos.shape[1]
    return [
        start + _pair_index(combos[:, left], combos[:, right], groups)
        for left in range(arity)
        for right in range(left + 1, arity)
    ]


def build_fixed_high_matrix(
    spec: Any,
    bucket_group_map: Sequence[int] | GroupPartition,
    *,
    settings: FineUnaryLargeSettings | None = None,
) -> tuple[csr_matrix, np.ndarray, FineUnaryContext, FineUnaryLayout, dict[str, Any]]:
    """Build all t-label rows, homogeneous lower seeds, and safe upper seeds."""

    config = settings or FineUnaryLargeSettings()
    context = _fine_context(spec, bucket_group_map)
    layout = _layout(context)
    multiset_counts = {d: comb(layout.groups + d - 1, d) for d in ARITIES}
    if sum(multiset_counts.values()) > config.max_group_multisets:
        raise ValueError("group multiset enumeration exceeds configured cap")
    labels = np.arange(layout.labels, dtype=np.int32)
    signs = labels // context.low.buckets
    blocks: list[csr_matrix] = []
    bounds: list[np.ndarray] = []
    family_counts: dict[str, Any] = {}

    # Arity-specific exact minima of u_d(label)+w_d*c_lambda(label,bit).
    cost_rows = 0
    for arity in ARITIES:
        weight = context.weights[arity - 1]
        unary_start = layout.unary_blocks[arity].start
        for family, bits in (
            ("u", (1 - signs,)),
            ("s", (signs,)),
            ("a", (np.zeros(layout.labels, dtype=np.int32), np.ones(layout.labels, dtype=np.int32))),
        ):
            for bit in bits:
                lambda_base = 1 + 4 * (labels % context.low.buckets) + 2 * bit
                block = _sparse_block(
                    layout.width,
                    layout.labels,
                    (
                        layout.t_blocks[(arity, family)].start + context.label_groups,
                        unary_start + labels,
                        lambda_base,
                        lambda_base + 1,
                    ),
                    (1.0, -1.0, -weight * context.low.g[:, 0], -weight * context.low.g[:, 1]),
                )
                blocks.append(block)
                bounds.append(np.zeros(layout.labels, dtype=np.float64))
                cost_rows += layout.labels

    lower_rows = seed_upper_rows = 0
    seed_lower_keys: list[tuple[str, int, tuple[int, ...], int]] = []
    seed_keys: list[tuple[int, tuple[int, ...]]] = []
    representatives = np.asarray(
        [members[int(np.argmax(context.failures[members]))] for members in context.members],
        dtype=np.int32,
    )
    for arity in ARITIES:
        combos = _multisets(layout.groups, arity)
        count = len(combos)
        k_columns = _pair_columns(combos, layout.k_blocks[arity].start, layout.groups)
        # The full lower family is priced exactly after every solve.  Seed
        # only homogeneous group multisets, then append every genuinely
        # violated true group row.  This removes 264,879 inactive P500 rows
        # from the first master without weakening completion semantics.
        homogeneous = np.repeat(
            np.arange(layout.groups, dtype=np.int32)[:, None], arity, axis=1
        )
        homogeneous_k = _pair_columns(
            homogeneous, layout.k_blocks[arity].start, layout.groups
        )
        blocks.append(
            _sparse_block(
                layout.width,
                layout.groups,
                (
                    *homogeneous_k,
                    *(
                        layout.t_blocks[(arity, "u")].start + homogeneous[:, p]
                        for p in range(arity)
                    ),
                ),
                tuple([-1.0] * (len(homogeneous_k) + arity)),
            )
        )
        bounds.append(np.zeros(layout.groups, dtype=np.float64))
        sat_terms = [np.full(layout.groups, layout.rho, dtype=np.int32)]
        sat_terms += homogeneous_k
        sat_terms.append(layout.t_blocks[(arity, "s")].start + homogeneous[:, 0])
        sat_terms += [
            layout.t_blocks[(arity, "a")].start + homogeneous[:, p]
            for p in range(1, arity)
        ]
        blocks.append(
            _sparse_block(
                layout.width,
                layout.groups,
                sat_terms,
                tuple([1.0] + [-1.0] * (len(sat_terms) - 1)),
            )
        )
        bounds.append(np.zeros(layout.groups, dtype=np.float64))
        for group in range(layout.groups):
            combo = tuple([group] * arity)
            seed_lower_keys.append(("u", arity, combo, -1))
            seed_lower_keys.append(("s", arity, combo, group))
        lower_rows += 2 * layout.groups
        conceptual_satisfied_rows = int(
            sum(len(set(map(int, row))) for row in combos)
        )

        fine = representatives[combos]
        unary_columns = [layout.unary_blocks[arity].start + fine[:, p] for p in range(arity)]
        blocks.append(
            _sparse_block(
                layout.width,
                count,
                (*k_columns, *unary_columns),
                tuple([1.0] * (len(k_columns) + arity)),
            )
        )
        bounds.append(1.0 - np.prod(context.failures[fine], axis=1))
        seed_keys.extend((arity, tuple(map(int, row))) for row in fine)
        seed_upper_rows += count
        family_counts[str(arity)] = {
            "group_multisets": count,
            "conceptual_lower_unsatisfied_rows": count,
            "conceptual_lower_satisfied_rows": conceptual_satisfied_rows,
            "initial_lower_unsatisfied_seed_rows": layout.groups,
            "initial_lower_satisfied_seed_rows": layout.groups,
            "initial_lower_seed_rows": 2 * layout.groups,
            "initial_upper_seed_rows": count,
        }

    matrix = vstack(blocks, format="csr")
    rhs = np.concatenate(bounds)
    expected = cost_rows + lower_rows + seed_upper_rows
    if matrix.shape != (expected, layout.width):
        raise AssertionError("fixed high matrix row accounting drifted")
    if expected > config.max_active_rows:
        raise ValueError("fixed high rows exceed configured active-row cap")
    csr_bytes = int(matrix.data.nbytes + matrix.indices.nbytes + matrix.indptr.nbytes)
    if csr_bytes > config.max_csr_bytes:
        raise MemoryError("fixed high matrix exceeds configured CSR cap")
    metadata = {
        "cost_rows": cost_rows,
        "lower_rows": lower_rows,
        "initial_upper_seed_rows": seed_upper_rows,
        "fixed_rows": expected,
        "fixed_nnz": int(matrix.nnz),
        "fixed_csr_bytes": csr_bytes,
        "family_counts": family_counts,
        "group_multisets": sum(multiset_counts.values()),
        "initial_upper_keys": tuple(seed_keys),
        "initial_lower_keys": tuple(seed_lower_keys),
    }
    return matrix, rhs, context, layout, metadata


def _upper_rows(
    context: FineUnaryContext,
    layout: FineUnaryLayout,
    keys: Sequence[tuple[int, tuple[int, ...]]],
) -> tuple[csr_matrix, np.ndarray]:
    row_indices: list[int] = []
    columns: list[int] = []
    values: list[float] = []
    rhs: list[float] = []
    for row, (arity, raw_labels) in enumerate(keys):
        labels = tuple(sorted(map(int, raw_labels)))
        if arity not in ARITIES or len(labels) != arity or any(
            label < 0 or label >= layout.labels for label in labels
        ):
            raise ValueError("invalid actual fine upper-row key")
        groups = context.label_groups[list(labels)]
        for endpoint, label in enumerate(labels):
            row_indices.append(row)
            columns.append(layout.unary_blocks[arity].start + label)
            values.append(1.0)
            for right in labels[endpoint + 1 :]:
                row_indices.append(row)
                columns.append(
                    layout.k_blocks[arity].start
                    + int(_pair_index(context.label_groups[label], context.label_groups[right], layout.groups))
                )
                values.append(1.0)
        rhs.append(1.0 - float(np.prod(context.failures[list(labels)])))
    matrix = coo_matrix(
        (values, (row_indices, columns)), shape=(len(keys), layout.width)
    ).tocsr()
    matrix.sum_duplicates()
    matrix.eliminate_zeros()
    matrix.sort_indices()
    return matrix, np.asarray(rhs, dtype=np.float64)


def _lower_rows(
    layout: FineUnaryLayout,
    keys: Sequence[tuple[str, int, tuple[int, ...], int]],
) -> tuple[csr_matrix, np.ndarray]:
    row_indices: list[int] = []
    columns: list[int] = []
    values: list[float] = []
    for row, (kind, arity, combo, forced_group) in enumerate(keys):
        groups = tuple(map(int, combo))
        if (
            kind not in ("u", "s")
            or arity not in ARITIES
            or len(groups) != arity
            or tuple(sorted(groups)) != groups
            or any(group < 0 or group >= layout.groups for group in groups)
            or (kind == "u" and forced_group != -1)
            or (kind == "s" and forced_group not in groups)
        ):
            raise ValueError("invalid fine-unary lower group-row key")
        if kind == "s":
            row_indices.append(row)
            columns.append(layout.rho)
            values.append(1.0)
        for left in range(arity):
            for right in range(left + 1, arity):
                row_indices.append(row)
                columns.append(
                    layout.k_blocks[arity].start
                    + int(_pair_index(groups[left], groups[right], layout.groups))
                )
                values.append(-1.0)
        forced_used = False
        for group in groups:
            if kind == "u":
                family = "u"
            elif group == forced_group and not forced_used:
                family = "s"
                forced_used = True
            else:
                family = "a"
            row_indices.append(row)
            columns.append(layout.t_blocks[(arity, family)].start + group)
            values.append(-1.0)
    matrix = coo_matrix(
        (values, (row_indices, columns)), shape=(len(keys), layout.width)
    ).tocsr()
    matrix.sum_duplicates()
    matrix.eliminate_zeros()
    matrix.sort_indices()
    return matrix, np.zeros(len(keys), dtype=np.float64)


def _k_sums(combos: np.ndarray, table: np.ndarray, groups: int) -> np.ndarray:
    result = np.zeros(len(combos), dtype=np.float64)
    for left in range(combos.shape[1]):
        for right in range(left + 1, combos.shape[1]):
            result += table[_pair_index(combos[:, left], combos[:, right], groups)]
    return result


class _PrefixUpperOracle:
    def __init__(self, context: FineUnaryContext, unary: np.ndarray):
        self.context = context
        self.unary = np.asarray(unary, dtype=np.float64)
        # A label dominated on S+zP for every z in [0,1] can never become
        # optimal after multiplication by a prefix/future failure product.
        # Build this exact (conservative on ambiguous float orientations)
        # one-label hull once per group and reuse it for every coarse tuple.
        self.group_envelopes = tuple(
            _pareto_envelope(
                context.failures[members],
                self.unary[members],
                np.asarray(members, dtype=np.int32)[:, None],
            )
            for members in context.members
        )
        self.cache: dict[tuple[int, ...], Envelope] = {
            (): Envelope(
                np.ones(1, dtype=np.float64),
                np.zeros(1, dtype=np.float64),
                np.empty((1, 0), dtype=np.int32),
            )
        }
        self.maximum_frontier = max(
            [1, *(len(envelope.products) for envelope in self.group_envelopes)]
        )
        self.expanded_states = 0

    def frontier(self, prefix: tuple[int, ...]) -> Envelope:
        result = self.cache.get(prefix)
        if result is not None:
            return result
        parent = self.frontier(prefix[:-1])
        group = prefix[-1]
        base = self.group_envelopes[group]
        self.expanded_states += len(parent.products) * len(base.products)
        result = _combine_envelopes(parent, base)
        self.maximum_frontier = max(self.maximum_frontier, len(result.products))
        self.cache[prefix] = result
        return result

    def maximize(self, groups: tuple[int, ...], *, cache_final: bool = False):
        if cache_final:
            frontier = self.frontier(groups)
        else:
            parent = self.frontier(groups[:-1])
            group = groups[-1]
            value, path, expanded = _maximize_terminal(parent, self.group_envelopes[group])
            self.expanded_states += expanded
            # Normalize the selected path with the same NumPy reduction order
            # used by the independent brute/semantic checker.  The argmax is
            # unchanged; this only removes sub-ulp associativity drift from
            # cached prefix products/sums.
            value = float(
                np.prod(self.context.failures[list(path)])
                + np.sum(self.unary[list(path)])
            )
            return value, path
        objective = frontier.products + frontier.sums
        index = int(np.argmax(objective))
        return float(objective[index]), tuple(sorted(map(int, frontier.paths[index])))


def scan_upper_complete(
    context: FineUnaryContext,
    layout: FineUnaryLayout,
    vector: Sequence[float],
    *,
    tolerance: float,
) -> dict[str, Any]:
    """Cover every coarse multiset and exactly price every needed fine tuple."""

    started = perf_counter()
    values = np.asarray(vector, dtype=np.float64)
    if values.shape != (layout.width,) or not np.all(np.isfinite(values)):
        raise ValueError("invalid fine-unary solver vector")
    violations: dict[tuple[int, tuple[int, ...]], float] = {}
    minimum_slack = np.inf
    argmin: dict[str, Any] | None = None
    exact_priced = screened = maximum_frontier = expanded_states = 0
    family_minima: dict[str, float] = {}
    for arity in ARITIES:
        combos = _multisets(layout.groups, arity)
        unary = values[layout.unary_blocks[arity]]
        table = values[layout.k_blocks[arity]]
        ksum = _k_sums(combos, table, layout.groups)
        max_failure = np.asarray(
            [float(np.max(context.failures[members])) for members in context.members]
        )
        max_unary = np.asarray([float(np.max(unary[members])) for members in context.members])
        safe_max = np.prod(max_failure[combos], axis=1) + np.sum(max_unary[combos], axis=1)
        lower_slack = 1.0 - ksum - safe_max
        oracle = _PrefixUpperOracle(context, unary)
        family_minimum = np.inf
        for index, raw_groups in enumerate(combos):
            groups = tuple(map(int, raw_groups))
            if lower_slack[index] >= -tolerance:
                slack = float(lower_slack[index])
                labels = None
                screened += 1
            else:
                maximum, labels = oracle.maximize(groups)
                slack = 1.0 - float(ksum[index]) - maximum
                exact_priced += 1
                if slack < -tolerance:
                    key = (arity, labels)
                    violations[key] = max(violations.get(key, 0.0), -slack)
            if slack < family_minimum:
                family_minimum = slack
            if slack < minimum_slack:
                minimum_slack = slack
                argmin = {
                    "arity": arity,
                    "groups": list(groups),
                    "fine_labels": None if labels is None else list(labels),
                    "safe_bound_only": labels is None,
                }
        family_minima[f"d{arity}_upper"] = float(family_minimum)
        maximum_frontier = max(maximum_frontier, oracle.maximum_frontier)
        expanded_states += oracle.expanded_states
    return {
        "minimum_slack": float(minimum_slack),
        "family_minima": family_minima,
        "argmin": argmin,
        "violations": violations,
        "coarse_multisets_checked": sum(
            comb(layout.groups + arity - 1, arity) for arity in ARITIES
        ),
        "safe_bound_screened": screened,
        "exact_dp_priced": exact_priced,
        "maximum_frontier": maximum_frontier,
        "expanded_states": expanded_states,
        "all_fine_upper_rows_covered": True,
        "sampling_used": False,
        "elapsed_seconds": perf_counter() - started,
    }


def _tighten_t(
    context: FineUnaryContext,
    layout: FineUnaryLayout,
    vector: np.ndarray,
) -> np.ndarray:
    lambdas = vector[layout.lambda_start : layout.lambda_stop]
    lambdas[:] = np.maximum(lambdas, 0.0)
    costs = _costs(context.low, lambdas)
    labels = np.arange(layout.labels)
    signs = labels // context.low.buckets
    for arity in ARITIES:
        unary = vector[layout.unary_blocks[arity]]
        weight = context.weights[arity - 1]
        per_family = {
            "u": unary + weight * costs[labels, 1 - signs],
            "a": unary + weight * np.min(costs, axis=1),
            "s": unary + weight * costs[labels, signs],
        }
        for family, endpoint_values in per_family.items():
            minima = np.full(layout.groups, np.inf, dtype=np.float64)
            np.minimum.at(minima, context.label_groups, endpoint_values)
            vector[layout.t_blocks[(arity, family)]] = minima
    return costs


def scan_lower_complete(
    context: FineUnaryContext,
    layout: FineUnaryLayout,
    vector: Sequence[float],
    *,
    tolerance: float = 1e-9,
) -> dict[str, Any]:
    """Exact group-minimum replay for every fine typed d3/d4/d5 atom."""

    started = perf_counter()
    values = np.asarray(vector, dtype=np.float64).copy()
    costs = _tighten_t(context, layout, values)
    rho = float(values[layout.rho])
    labels = np.arange(layout.labels)
    signs = labels // context.low.buckets
    families: dict[str, float] = {}
    argmins: dict[str, Any] = {}
    violations: dict[tuple[str, int, tuple[int, ...], int], float] = {}
    minimum = np.inf
    for arity in ARITIES:
        combos = _multisets(layout.groups, arity)
        table = values[layout.k_blocks[arity]]
        ksum = _k_sums(combos, table, layout.groups)
        unary = values[layout.unary_blocks[arity]]
        weight = context.weights[arity - 1]
        endpoint = {
            "u": unary + weight * costs[labels, 1 - signs],
            "a": unary + weight * np.min(costs, axis=1),
            "s": unary + weight * costs[labels, signs],
        }
        minima: dict[str, np.ndarray] = {}
        arglabel: dict[str, np.ndarray] = {}
        for family, endpoint_values in endpoint.items():
            minimum_values = np.full(layout.groups, np.inf, dtype=np.float64)
            minimum_labels = np.full(layout.groups, -1, dtype=np.int32)
            for group, members in enumerate(context.members):
                local = int(np.argmin(endpoint_values[members]))
                minimum_values[group] = endpoint_values[members[local]]
                minimum_labels[group] = members[local]
            minima[family] = minimum_values
            arglabel[family] = minimum_labels
        unsat = ksum + np.sum(minima["u"][combos], axis=1)
        ui = int(np.argmin(unsat))
        families[f"d{arity}_unsatisfied"] = float(unsat[ui])
        argmins[f"d{arity}_unsatisfied"] = {
            "groups": combos[ui].tolist(),
            "labels": arglabel["u"][combos[ui]].tolist(),
        }
        for index in np.flatnonzero(unsat < -tolerance):
            key = ("u", arity, tuple(map(int, combos[int(index)])), -1)
            violations[key] = -float(unsat[int(index)])
        sat_best = np.inf
        sat_key = None
        base = ksum + np.sum(minima["a"][combos], axis=1) - rho
        for position in range(arity):
            selected = (
                np.ones(len(combos), dtype=bool)
                if position == 0
                else combos[:, position] != combos[:, position - 1]
            )
            local_indices = np.flatnonzero(selected)
            local_groups = combos[selected, position]
            slack = base[selected] + minima["s"][local_groups] - minima["a"][local_groups]
            index = int(np.argmin(slack))
            if float(slack[index]) < sat_best:
                source = int(local_indices[index])
                forced = int(local_groups[index])
                sat_best = float(slack[index])
                fine = arglabel["a"][combos[source]].copy()
                occurrences = np.flatnonzero(combos[source] == forced)
                fine[int(occurrences[0])] = arglabel["s"][forced]
                sat_key = {"groups": combos[source].tolist(), "labels": fine.tolist(), "forced_group": forced}
            for local_index in np.flatnonzero(slack < -tolerance):
                source = int(local_indices[int(local_index)])
                forced = int(local_groups[int(local_index)])
                key = ("s", arity, tuple(map(int, combos[source])), forced)
                violations[key] = max(
                    violations.get(key, 0.0), -float(slack[int(local_index)])
                )
        families[f"d{arity}_satisfied"] = sat_best
        argmins[f"d{arity}_satisfied"] = sat_key
        minimum = min(minimum, float(unsat[ui]), sat_best)
    return {
        "minimum_slack": float(minimum),
        "families": families,
        "argmins": argmins,
        "violations": violations,
        "all_fine_typed_rows_checked": True,
        "sampling_used": False,
        "elapsed_seconds": perf_counter() - started,
    }


def lift_group_witness(
    spec: Any,
    bucket_group_map: Sequence[int] | GroupPartition,
    *,
    rho: float,
    lambdas: Sequence[float],
    pair_tables: Mapping[int | str, Sequence[float]],
) -> dict[str, Any]:
    """Embed an existing coarse-pair witness by setting every fine unary to 0."""

    context = _fine_context(spec, bucket_group_map)
    layout = _layout(context)
    lam = tuple(map(float, lambdas))
    if len(lam) != 4 * context.low.buckets or any(not isfinite(value) or value < 0 for value in lam):
        raise ValueError("group witness has invalid lambda values")
    tables: dict[str, list[float]] = {}
    for arity in ARITIES:
        raw = pair_tables.get(str(arity), pair_tables.get(arity))
        if raw is None:
            raise ValueError("group witness is missing a pair table")
        values = list(map(float, raw))
        if len(values) != layout.pairs or any(not isfinite(value) for value in values):
            raise ValueError("group witness pair-table dimension mismatch")
        tables[str(arity)] = values
    return {
        "rho": float(rho),
        "lambdas": list(lam),
        "unary_tables": {str(arity): [0.0] * layout.labels for arity in ARITIES},
        "pair_tables": tables,
    }


def _vector_from_witness(
    context: FineUnaryContext,
    layout: FineUnaryLayout,
    witness: Mapping[str, Any],
) -> np.ndarray:
    vector = np.zeros(layout.width, dtype=np.float64)
    rho = float(witness.get("rho"))
    lambdas = np.asarray(witness.get("lambdas"), dtype=np.float64)
    if not isfinite(rho) or not 0 <= rho <= 1 or lambdas.shape != (
        4 * context.low.buckets,
    ) or not np.all(np.isfinite(lambdas)) or np.any(lambdas < 0):
        raise ValueError("invalid fine-unary rho/lambda witness")
    unary_tables = witness.get("unary_tables")
    pair_tables = witness.get("pair_tables")
    if not isinstance(unary_tables, Mapping) or set(unary_tables) != {"3", "4", "5"}:
        raise ValueError("fine-unary witness must contain exactly u3/u4/u5")
    if not isinstance(pair_tables, Mapping) or set(pair_tables) != {"3", "4", "5"}:
        raise ValueError("fine-unary witness must contain exactly K3/K4/K5")
    vector[layout.rho] = rho
    vector[layout.lambda_start : layout.lambda_stop] = lambdas
    for arity in ARITIES:
        unary = np.asarray(unary_tables[str(arity)], dtype=np.float64)
        table = np.asarray(pair_tables[str(arity)], dtype=np.float64)
        if (
            unary.shape != (layout.labels,)
            or table.shape != (layout.pairs,)
            or not np.all(np.isfinite(unary))
            or not np.all(np.isfinite(table))
        ):
            raise ValueError("fine-unary witness table dimension mismatch")
        vector[layout.unary_blocks[arity]] = unary
        vector[layout.k_blocks[arity]] = table
    _tighten_t(context, layout, vector)
    return vector


def _decode_witness(
    context: FineUnaryContext, layout: FineUnaryLayout, vector: Sequence[float]
) -> dict[str, Any]:
    values = np.asarray(vector, dtype=np.float64)
    return {
        "rho": float(values[layout.rho]),
        "lambdas": values[layout.lambda_start : layout.lambda_stop].tolist(),
        "unary_tables": {
            str(arity): values[layout.unary_blocks[arity]].tolist() for arity in ARITIES
        },
        "pair_tables": {
            str(arity): values[layout.k_blocks[arity]].tolist() for arity in ARITIES
        },
    }


def check_fine_unary_witness(
    spec: Any,
    bucket_group_map: Sequence[int] | GroupPartition,
    witness: Mapping[str, Any],
    *,
    tolerance: float = 1e-9,
    low_block_size: int = 128,
    max_group_multisets: int = 100_000,
) -> dict[str, Any]:
    """Independent complete numerical replay; no LP matrix or t value is read."""

    started = perf_counter()
    if not 1e-10 <= tolerance <= 1e-7:
        raise ValueError("semantic tolerance must lie in [1e-10,1e-7]")
    context = _fine_context(spec, bucket_group_map)
    layout = _layout(context)
    count = sum(comb(layout.groups + arity - 1, arity) for arity in ARITIES)
    if count > max_group_multisets:
        raise ValueError("semantic group enumeration exceeds resource cap")
    vector = _vector_from_witness(context, layout, witness)
    rho = float(vector[layout.rho])
    costs = _costs(context.low, vector[layout.lambda_start : layout.lambda_stop])
    low_scan = _scan(context.low, costs, low_block_size)
    low = _summary(context.low, low_scan, tolerance)
    low_slack = min(
        min(low["min_unsatisfied_by_arity"].values()),
        low["min_satisfied_bound"] - rho,
    )
    upper = scan_upper_complete(context, layout, vector, tolerance=tolerance)
    lower = scan_lower_complete(context, layout, vector, tolerance=tolerance)
    minimum = min(low_slack, upper["minimum_slack"], lower["minimum_slack"])
    ok = bool(
        minimum >= -tolerance
        and not upper["violations"]
        and not lower["violations"]
        and low["all_low_order_pairs_scanned"]
        and upper["all_fine_upper_rows_covered"]
        and lower["all_fine_typed_rows_checked"]
    )
    return {
        "schema_version": "v016-fine-unary-large-complete-floating-check-v1",
        "ok": ok,
        "status": "floating_complete_row_check" if ok else "infeasible_floating_witness",
        "rho": rho,
        "minimum_slack": float(minimum),
        "low_order": low,
        "upper": {key: value for key, value in upper.items() if key != "violations"},
        "lower": {key: value for key, value in lower.items() if key != "violations"},
        "all_low_order_rows_checked": True,
        "all_fine_upper_rows_covered": True,
        "all_fine_typed_rows_checked": True,
        "complete_separation": True,
        "sampling_used": False,
        "uses_lp_matrix_for_check": False,
        "is_exact_certificate": False,
        "verified_rho": None,
        "elapsed_seconds": perf_counter() - started,
    }


class _PersistentMaster:
    """Candidate-local append-only public Highs model."""

    def __init__(
        self,
        objective: np.ndarray,
        bounds: Sequence[tuple[float | None, float | None]],
        *,
        backend: PersistentBackendSpec,
        highspy_site: str | Path | None,
    ) -> None:
        self.highspy, self.highspy_site = _load_highspy(highspy_site)
        self.highs = self.highspy.Highs()
        self.nvars = len(objective)
        self.rows = 0
        self.solve_calls = 0
        self.successful_solves = 0
        self.closed = False
        for name, value in (
            ("output_flag", backend.output_flag),
            ("log_to_console", backend.output_flag),
            ("solver", "simplex"),
            ("simplex_strategy", backend.simplex_strategy),
            ("presolve", "on" if backend.presolve else "off"),
            ("threads", backend.threads),
            ("parallel", "off"),
        ):
            self._checked(self.highs.setOptionValue(name, value), f"setOptionValue({name})")
        lower = np.asarray(
            [-self.highspy.kHighsInf if item[0] is None else float(item[0]) for item in bounds],
            dtype=np.float64,
        )
        upper = np.asarray(
            [self.highspy.kHighsInf if item[1] is None else float(item[1]) for item in bounds],
            dtype=np.float64,
        )
        if lower.shape != (self.nvars,) or upper.shape != (self.nvars,) or np.any(lower > upper):
            raise PersistentBackendError("invalid persistent fine-unary bounds")
        self._checked(self.highs.addVars(self.nvars, lower, upper), "addVars")
        columns = np.arange(self.nvars, dtype=np.int32)
        self._checked(
            self.highs.changeColsCost(
                self.nvars, columns, np.asarray(objective, dtype=np.float64)
            ),
            "changeColsCost",
        )

    def _checked(self, status: Any, operation: str) -> None:
        if status != self.highspy.HighsStatus.kOk:
            raise PersistentBackendError(f"HiGHS {operation} failed: {status}")

    def append(self, matrix: csr_matrix, rhs: np.ndarray) -> int:
        block = csr_matrix(matrix, dtype=np.float64)
        block.sum_duplicates()
        block.eliminate_zeros()
        block.sort_indices()
        upper = np.asarray(rhs, dtype=np.float64)
        count = block.shape[0]
        if (
            block.shape[1] != self.nvars
            or upper.shape != (count,)
            or not np.all(np.isfinite(block.data))
            or not np.all(np.isfinite(upper))
        ):
            raise PersistentBackendError("malformed persistent fine-unary row batch")
        lower = np.full(count, -self.highspy.kHighsInf, dtype=np.float64)
        self._checked(
            self.highs.addRows(
                count,
                lower,
                upper,
                block.nnz,
                np.asarray(block.indptr, dtype=np.int32),
                np.asarray(block.indices, dtype=np.int32),
                np.asarray(block.data, dtype=np.float64),
            ),
            "addRows",
        )
        self.rows += count
        return count

    def set_primal_start(self, vector: Sequence[float]) -> bool:
        values = np.asarray(vector, dtype=np.float64)
        if values.shape != (self.nvars,) or not np.all(np.isfinite(values)):
            raise PersistentBackendError("malformed fine-unary primal start")
        indices = np.arange(self.nvars, dtype=np.int32)
        self._checked(self.highs.setSolution(self.nvars, indices, values), "setSolution")
        return True

    def solve(self, *, additional_seconds: float, tolerance: float) -> dict[str, Any]:
        if self.closed or not isfinite(additional_seconds) or additional_seconds <= 0:
            raise PersistentBackendError("invalid persistent solve budget/state")
        basis = self.highs.getBasis()
        basis_valid = bool(getattr(basis, "valid", False))
        reapplied = False
        if self.successful_solves and basis_valid:
            self._checked(self.highs.setBasis(basis), "setBasis")
            reapplied = True
        cumulative_before = float(self.highs.getRunTime())
        for name, value in (
            ("time_limit", cumulative_before + float(additional_seconds)),
            ("primal_feasibility_tolerance", max(1e-10, tolerance / 10)),
            ("dual_feasibility_tolerance", max(1e-10, tolerance / 10)),
        ):
            self._checked(self.highs.setOptionValue(name, value), f"setOptionValue({name})")
        stage = perf_counter()
        run_status = self.highs.run()
        seconds = perf_counter() - stage
        if run_status not in (self.highspy.HighsStatus.kOk, self.highspy.HighsStatus.kWarning):
            raise PersistentBackendError(f"HiGHS run failed: {run_status}")
        status = self.highs.getModelStatus()
        solution = self.highs.getSolution()
        optimal = status == self.highspy.HighsModelStatus.kOptimal
        values = np.asarray(solution.col_value, dtype=np.float64) if solution.value_valid else None
        if values is not None and (values.shape != (self.nvars,) or not np.all(np.isfinite(values))):
            raise PersistentBackendError("HiGHS returned malformed fine-unary primal")
        self.solve_calls += 1
        if optimal:
            self.successful_solves += 1
        return {
            "optimal": optimal,
            "status": 0 if optimal else 1 if status in (
                self.highspy.HighsModelStatus.kTimeLimit,
                self.highspy.HighsModelStatus.kIterationLimit,
            ) else 2,
            "message": str(self.highs.modelStatusToString(status)),
            "values": values,
            "solve_seconds": seconds,
            "diagnostics": {
                "model_status": str(status),
                "run_status": str(run_status),
                "solve_call": self.solve_calls,
                "retained_rows": self.rows,
                "basis_valid_before": basis_valid,
                "basis_reapplied": reapplied,
                "basis_valid_after": bool(getattr(self.highs.getBasis(), "valid", False)),
                "simplex_iterations": int(self.highs.getInfo().simplex_iteration_count),
                "cumulative_runtime_before": cumulative_before,
                "cumulative_runtime_after": float(self.highs.getRunTime()),
            },
        }

    def close(self) -> None:
        if self.closed:
            return
        try:
            self.highs.clearModel()
            self.highs.releaseMemory()
        finally:
            self.closed = True


def _csr_bytes(matrix: csr_matrix) -> int:
    return int(matrix.data.nbytes + matrix.indices.nbytes + matrix.indptr.nbytes)


def solve_fine_unary_upper_persistent(
    spec: Any,
    bucket_group_map: Sequence[int] | GroupPartition,
    *,
    settings: FineUnaryLargeSettings | None = None,
    warm_cuts: Sequence[Sequence[int]] = (),
    initial_witness: Mapping[str, Any] | None = None,
    initial_witness_provenance: Mapping[str, Any] | None = None,
    backend: PersistentBackendSpec | None = None,
    highspy_site: str | Path | None = None,
) -> dict[str, Any]:
    """Maximize rho with complete L1/L2 and fine-unary high separation."""

    started = perf_counter()
    config = settings or FineUnaryLargeSettings()
    backend_config = backend or PersistentBackendSpec()
    fixed, fixed_rhs, context, layout, meta = build_fixed_high_matrix(
        spec, bucket_group_map, settings=config
    )
    build_seconds = perf_counter() - started
    keys: list[tuple[int, ...]] = [()]
    keys += [(endpoint,) for endpoint in range(4 * context.low.buckets)]
    keys += [(endpoint, endpoint) for endpoint in range(4 * context.low.buckets)]
    keys += _anchor_keys(context.low, config.seed_anchor_count)
    keys += [_valid_key(key, context.low.buckets) for key in warm_cuts]
    keys = list(dict.fromkeys(keys))
    if len(keys) > config.max_low_rows:
        raise ValueError("initial low rows exceed configured cap")
    low_matrix, low_rhs = _low_matrix(
        context.low,
        keys,
        np.arange(layout.low_width, dtype=np.int32),
        layout.width,
        0.0,
    )
    initial_rows = len(keys) + fixed.shape[0]
    if initial_rows > config.max_active_rows:
        raise ValueError("initial fine-unary active rows exceed configured cap")
    if _csr_bytes(low_matrix) + _csr_bytes(fixed) > config.max_csr_bytes:
        raise MemoryError("initial fine-unary active CSR exceeds configured cap")

    objective = np.zeros(layout.width, dtype=np.float64)
    objective[layout.rho] = -1.0
    bounds: list[tuple[float | None, float | None]] = [(None, None)] * layout.width
    bounds[layout.rho] = (0.0, 1.0)
    for column in range(layout.lambda_start, layout.lambda_stop):
        bounds[column] = (0.0, None)
    # Gauge: exactly one fine unary anchor per coarse label group and arity.
    anchors = [int(members[0]) for members in context.members]
    for arity in ARITIES:
        start = layout.unary_blocks[arity].start
        for label in anchors:
            bounds[start + label] = (0.0, 0.0)

    master = _PersistentMaster(
        objective, bounds, backend=backend_config, highspy_site=highspy_site
    )
    active_blocks: list[tuple[csr_matrix, np.ndarray]] = [(low_matrix, low_rhs), (fixed, fixed_rhs)]
    active_upper = set(meta["initial_upper_keys"])
    active_lower = set(meta["initial_lower_keys"])
    start_check = None
    primal_start_set = False
    try:
        stage = perf_counter()
        master.append(low_matrix, low_rhs)
        master.append(fixed, fixed_rhs)
        model_build_seconds = perf_counter() - stage
        if initial_witness is not None:
            start_check = check_fine_unary_witness(
                spec,
                context.partition,
                initial_witness,
                tolerance=config.tolerance,
                low_block_size=config.low_block_size,
                max_group_multisets=config.max_group_multisets,
            )
            if not start_check["ok"]:
                raise ValueError("initial fine-unary witness failed complete semantic replay")
            start_vector = _vector_from_witness(context, layout, initial_witness)
            primal_start_set = master.set_primal_start(start_vector)

        rounds: list[dict[str, Any]] = []
        status = "round_limit"
        vector = None
        solve_seconds = separation_seconds = append_seconds = 0.0
        max_active_bytes = _csr_bytes(low_matrix) + _csr_bytes(fixed)
        cut_config = LowOrderCGSpec(
            partners_per_label=config.partners_per_label,
            partner_selection="violated_spread",
            tolerance=config.tolerance,
            block_size=config.low_block_size,
        )
        for round_index in range(config.max_rounds):
            remaining = (
                config.time_limit_sec
                - (perf_counter() - started)
                - config.final_check_reserve_sec
            )
            if remaining <= 0:
                status = "solver_time_limit"
                break
            solved = master.solve(additional_seconds=remaining, tolerance=config.tolerance)
            solve_seconds += solved["solve_seconds"]
            run = {
                "round": round_index + 1,
                "low_rows": len(keys),
                "upper_rows": len(active_upper),
                "total_rows": master.rows,
                "solver_status": solved["status"],
                "solver_message": solved["message"],
                "solve_seconds": solved["solve_seconds"],
                "linear_backend": solved["diagnostics"],
            }
            rounds.append(run)
            if not solved["optimal"] or solved["values"] is None:
                status = "solver_time_limit" if solved["status"] == 1 else "solver_no_candidate"
                break
            candidate = np.asarray(solved["values"], dtype=np.float64).copy()
            if np.any(candidate[layout.lambda_start : layout.lambda_stop] < -config.tolerance):
                status = "negative_lambda"
                break
            costs = _tighten_t(context, layout, candidate)
            active_worst = max(
                float(np.max(matrix @ candidate - rhs))
                for matrix, rhs in active_blocks
                if matrix.shape[0]
            )
            run["max_active_matrix_violation"] = active_worst
            if not isfinite(active_worst) or active_worst > config.tolerance:
                status = "master_candidate_infeasible"
                break
            vector = candidate
            rho = float(candidate[layout.rho])
            stage = perf_counter()
            low_scan = _scan(context.low, costs, config.low_block_size)
            low = _summary(context.low, low_scan, config.tolerance)
            low_worst = max(
                low["max_unsatisfied_violation"], rho - low["min_satisfied_bound"], 0.0
            )
            upper = scan_upper_complete(
                context, layout, candidate, tolerance=config.tolerance
            )
            upper_worst = max(upper["violations"].values(), default=0.0)
            lower = scan_lower_complete(
                context, layout, candidate, tolerance=config.tolerance
            )
            lower_worst = max(lower["violations"].values(), default=0.0)
            separation_seconds += perf_counter() - stage
            run.update(
                rho=rho,
                max_low_order_violation=low_worst,
                max_fine_upper_violation=upper_worst,
                max_fine_lower_violation=lower_worst,
                upper_scan={key: value for key, value in upper.items() if key != "violations"},
                lower_scan={key: value for key, value in lower.items() if key != "violations"},
            )
            if (
                low_worst <= config.tolerance
                and upper_worst <= config.tolerance
                and lower_worst <= config.tolerance
            ):
                status = "complete_joint_numeric_candidate"
                break

            stage = perf_counter()
            active_low = set(keys)
            low_candidates = _pair_candidates(
                context.low,
                costs,
                rho,
                cut_config,
                active_low,
            )
            low_additions = sorted(
                low_candidates, key=lambda key: (-low_candidates[key], key)
            )[: config.add_low_rows_per_round]
            upper_additions = [
                key
                for key, _ in sorted(
                    upper["violations"].items(), key=lambda item: (-item[1], item[0])
                )
                if key not in active_upper
            ][: config.add_upper_rows_per_round]
            lower_additions = [
                key
                for key, _ in sorted(
                    lower["violations"].items(), key=lambda item: (-item[1], item[0])
                )
                if key not in active_lower
            ][: config.add_upper_rows_per_round]
            if not low_additions and not upper_additions and not lower_additions:
                status = "joint_separation_stalled"
                break
            if (
                len(keys) + len(low_additions) > config.max_low_rows
                or master.rows
                + len(low_additions)
                + len(upper_additions)
                + len(lower_additions)
                > config.max_active_rows
            ):
                status = "row_limit"
                break
            if low_additions:
                new_low, new_low_rhs = _low_matrix(
                    context.low,
                    low_additions,
                    np.arange(layout.low_width, dtype=np.int32),
                    layout.width,
                    0.0,
                )
                master.append(new_low, new_low_rhs)
                active_blocks.append((new_low, new_low_rhs))
                keys.extend(low_additions)
            if upper_additions:
                new_upper, new_upper_rhs = _upper_rows(context, layout, upper_additions)
                master.append(new_upper, new_upper_rhs)
                active_blocks.append((new_upper, new_upper_rhs))
                active_upper.update(upper_additions)
            if lower_additions:
                new_lower, new_lower_rhs = _lower_rows(layout, lower_additions)
                master.append(new_lower, new_lower_rhs)
                active_blocks.append((new_lower, new_lower_rhs))
                active_lower.update(lower_additions)
            append_seconds += perf_counter() - stage
            active_bytes = sum(_csr_bytes(matrix) for matrix, _ in active_blocks)
            max_active_bytes = max(max_active_bytes, active_bytes)
            if active_bytes > config.max_csr_bytes:
                status = "csr_memory_limit"
                break

        witness = None if vector is None else _decode_witness(context, layout, vector)
        check = None
        final_check_seconds = 0.0
        if witness is not None and status == "complete_joint_numeric_candidate":
            stage = perf_counter()
            check = check_fine_unary_witness(
                spec,
                context.partition,
                witness,
                tolerance=config.tolerance,
                low_block_size=config.low_block_size,
                max_group_multisets=config.max_group_multisets,
            )
            final_check_seconds = perf_counter() - stage
        ok = bool(check and check["ok"] and status == "complete_joint_numeric_candidate")
        if status == "complete_joint_numeric_candidate" and check is not None and not check["ok"]:
            status = "independent_semantic_check_failed"
        result = {
            "schema_version": SCHEMA_VERSION,
            "status": status,
            "ok": ok,
            "rho": witness["rho"] if ok else None,
            "witness": witness,
            "design_hash": spec.canonical_hash,
            "bucket_group_map": list(context.partition.bucket_groups),
            "bucket_group_map_sha256": _canonical_sha(list(context.partition.bucket_groups)),
            "settings": asdict(config),
            "backend": asdict(backend_config),
            "layout": {
                "variables": layout.width,
                "lambda_variables": layout.lambda_stop - layout.lambda_start,
                "fine_unary_variables": 3 * layout.labels,
                "fixed_unary_gauges": 3 * layout.groups,
                "t_variables": 9 * layout.groups,
                "pair_variables": 3 * layout.pairs,
            },
            "fixed_high": {
                key: value
                for key, value in meta.items()
                if key not in ("initial_upper_keys", "initial_lower_keys")
            },
            "rounds": rounds,
            "warm_cuts": [list(key) for key in keys],
            "active_upper_keys": [
                [arity, list(labels)] for arity, labels in sorted(active_upper)
            ],
            "active_lower_keys": [
                [kind, arity, list(groups), forced]
                for kind, arity, groups, forced in sorted(active_lower)
            ],
            "initial_witness": {
                "provided": initial_witness is not None,
                "primal_start_set": primal_start_set,
                "complete_semantic_precheck": None if start_check is None else start_check["ok"],
                "provenance": None
                if initial_witness_provenance is None
                else dict(initial_witness_provenance),
                "trusted_as_final_result": False,
            },
            "check": check,
            "all_low_order_rows_checked": bool(check and check["all_low_order_rows_checked"]),
            "all_fine_upper_rows_covered": bool(check and check["all_fine_upper_rows_covered"]),
            "all_fine_typed_rows_checked": bool(check and check["all_fine_typed_rows_checked"]),
            "complete_separation": bool(check and check["complete_separation"]),
            "sampling_used": False,
            "verified_rho": None,
            "is_exact_certificate": False,
            "is_full_certificate": False,
            "rho_semantics": "floating complete all-row candidate only; Fraction promotion required",
            "build_seconds": build_seconds,
            "model_build_seconds": model_build_seconds,
            "solve_seconds": solve_seconds,
            "separation_seconds": separation_seconds,
            "incremental_append_seconds": append_seconds,
            "final_check_seconds": final_check_seconds,
            "max_active_csr_bytes": max_active_bytes,
            "elapsed_seconds": perf_counter() - started,
            "source_sha256": {
                "v016_fine_unary_large.py": sha256(Path(__file__).read_bytes()).hexdigest()
            },
        }
        return result
    finally:
        master.close()


__all__ = [
    "ARITIES",
    "FineUnaryLargeSettings",
    "SCHEMA_VERSION",
    "brute_force_upper_tuple",
    "build_fixed_high_matrix",
    "check_fine_unary_witness",
    "lift_group_witness",
    "maximize_upper_tuple",
    "scan_lower_complete",
    "scan_upper_complete",
    "solve_fine_unary_upper_persistent",
]
