#!/usr/bin/env python3
"""Sparse search for weighted Max-2SAT snapshot certificates.

This is the follow-up to max2sat_snapshot_certificate_search.py.  It keeps the
same atom certificate, but allows the snapshot bias to use a general unary
weight

    b_v = (w(P_v^{(1)}-N_v^{(1)}) + (P_v^{(2)}-N_v^{(2)}))
          / (w(P_v^{(1)}+N_v^{(1)}) + (P_v^{(2)}+N_v^{(2)})).

Equivalently, in the finite dual LP a unary atom has endpoint weight w/2 while
each binary endpoint has weight 1/2.  The script uses a sparse LP matrix so that
large bucket counts are feasible.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from itertools import product
from pathlib import Path

import numpy as np
from scipy.optimize import differential_evolution, linprog
from scipy.sparse import coo_matrix, csr_matrix


P24 = np.array(
    [
        0.0355062601,
        0.0682550983,
        0.1327459330,
        0.1839187593,
        0.1853714207,
        0.2270974058,
        0.2292088057,
        0.2328767651,
        0.2834950959,
        0.2981107773,
        0.3819696907,
        0.4596771264,
        0.5403228736,
        0.6180303093,
        0.7018892227,
        0.7165049041,
        0.7671232349,
        0.7707911943,
        0.7729025942,
        0.8146285793,
        0.8160812407,
        0.8672540670,
        0.9317449017,
        0.9644937399,
    ],
    dtype=float,
)


def lit_sat(sign: int, bit: int) -> bool:
    return (sign == 0 and bit == 1) or (sign == 1 and bit == 0)


def symmetric_from_half(x: np.ndarray, L: int) -> np.ndarray:
    h = L // 2
    lower = np.sort(np.clip(np.asarray(x[:h], dtype=float), 0.0, 0.5))
    if L % 2 == 0:
        return np.concatenate([lower, 1.0 - lower[::-1]])
    return np.concatenate([lower, np.array([0.5]), 1.0 - lower[::-1]])


def symmetrize_monotone(p: np.ndarray) -> np.ndarray:
    p = np.asarray(p, dtype=float)
    p = (p + 1.0 - p[::-1]) / 2.0
    return np.maximum.accumulate(np.clip(p, 0.0, 1.0))


def interpolate_p(source: np.ndarray, L: int) -> np.ndarray:
    source = np.asarray(source, dtype=float)
    L0 = len(source)
    x0 = np.linspace(-1.0 + 1.0 / L0, 1.0 - 1.0 / L0, L0)
    x = np.linspace(-1.0 + 1.0 / L, 1.0 - 1.0 / L, L)
    return symmetrize_monotone(np.interp(x, x0, source))


def interpolate_p_at(source: np.ndarray, centers: np.ndarray) -> np.ndarray:
    source = np.asarray(source, dtype=float)
    L0 = len(source)
    x0 = np.linspace(-1.0 + 1.0 / L0, 1.0 - 1.0 / L0, L0)
    return symmetrize_monotone(np.interp(centers, x0, source))


def interpolate_p_between_intervals(
    source: np.ndarray, source_intervals: np.ndarray, target_intervals: np.ndarray
) -> np.ndarray:
    source = np.asarray(source, dtype=float)
    source_centers = interval_centers(np.asarray(source_intervals, dtype=float))
    target_centers = interval_centers(np.asarray(target_intervals, dtype=float))
    return symmetrize_monotone(np.interp(target_centers, source_centers, source))


def uniform_intervals(L: int) -> np.ndarray:
    return np.column_stack(
        [
            -1.0 + 2.0 * np.arange(L, dtype=float) / L,
            -1.0 + 2.0 * np.arange(1, L + 1, dtype=float) / L,
        ]
    )


def interval_centers(intervals: np.ndarray) -> np.ndarray:
    return (intervals[:, 0] + intervals[:, 1]) / 2.0


def make_power_intervals(L: int, power: float) -> np.ndarray:
    """Symmetric partition with boundary map sign(t)|t|^power."""
    t = np.linspace(-1.0, 1.0, L + 1)
    b = np.sign(t) * (np.abs(t) ** power)
    b[0] = -1.0
    b[-1] = 1.0
    b[L // 2] = 0.0
    return np.column_stack([b[:-1], b[1:]])


def make_focus_intervals(L: int, focus: float, strength: float, sigma: float) -> np.ndarray:
    """Symmetric partition with extra density around +/- focus.

    The positive half is generated by inverting a smooth density
        1 + strength * exp(-(x-focus)^2/(2 sigma^2)).
    Reflection gives the negative half.
    """
    if L % 2:
        raise ValueError("focus intervals currently require even L")
    h = L // 2
    grid = np.linspace(0.0, 1.0, 20001)
    density = 1.0 + strength * np.exp(-0.5 * ((grid - focus) / sigma) ** 2)
    cdf = np.concatenate([[0.0], np.cumsum((density[:-1] + density[1:]) * np.diff(grid) / 2.0)])
    cdf /= cdf[-1]
    pos = np.interp(np.linspace(0.0, 1.0, h + 1), cdf, grid)
    b = np.concatenate([-pos[:0:-1], pos])
    b[0] = -1.0
    b[-1] = 1.0
    b[h] = 0.0
    return np.column_stack([b[:-1], b[1:]])


def make_multi_focus_intervals(L: int, components: list[tuple[float, float, float]]) -> np.ndarray:
    """Symmetric partition with extra density around several positive-half foci."""
    if L % 2:
        raise ValueError("multi-focus intervals currently require even L")
    h = L // 2
    grid = np.linspace(0.0, 1.0, 30001)
    density = np.ones_like(grid)
    for focus, strength, sigma in components:
        if sigma <= 0:
            raise ValueError("focus sigma must be positive")
        density += strength * np.exp(-0.5 * ((grid - focus) / sigma) ** 2)
    cdf = np.concatenate([[0.0], np.cumsum((density[:-1] + density[1:]) * np.diff(grid) / 2.0)])
    cdf /= cdf[-1]
    pos = np.interp(np.linspace(0.0, 1.0, h + 1), cdf, grid)
    b = np.concatenate([-pos[:0:-1], pos])
    b[0] = -1.0
    b[-1] = 1.0
    b[h] = 0.0
    return np.column_stack([b[:-1], b[1:]])


def parse_focus_component(value: str) -> tuple[float, float, float]:
    parts = value.replace(",", ":").split(":")
    if len(parts) != 3:
        raise argparse.ArgumentTypeError("focus components must be focus:strength:sigma")
    return tuple(map(float, parts))  # type: ignore[return-value]


def format_probs(p: np.ndarray) -> str:
    return "[" + ", ".join(f"{x:.10f}" for x in p) + "]"


@dataclass
class SolveResult:
    L: int
    unary_weight: float
    rho: float
    min_slack: float
    min_row: int
    p: np.ndarray
    lambdas: np.ndarray
    intervals: np.ndarray
    success: bool
    message: str

    def as_jsonable(self) -> dict:
        return {
            "L": self.L,
            "unary_weight": self.unary_weight,
            "rho": self.rho,
            "min_slack": self.min_slack,
            "min_row": self.min_row,
            "p": [float(x) for x in self.p],
            "lambdas": [float(x) for x in self.lambdas],
            "intervals": [[float(a), float(b)] for a, b in self.intervals],
            "success": self.success,
            "message": self.message,
        }


class SparseCertificateModel:
    def __init__(self, L: int, unary_weight: float, intervals: np.ndarray | None = None):
        self.L = L
        self.unary_weight = float(unary_weight)
        self.unary_endpoint_weight = self.unary_weight / 2.0
        self.intervals = np.asarray(intervals if intervals is not None else uniform_intervals(L), dtype=float)
        if self.intervals.shape != (L, 2):
            raise ValueError(f"expected intervals shape {(L, 2)}, got {self.intervals.shape}")
        if abs(self.intervals[0, 0] + 1.0) > 1e-10 or abs(self.intervals[-1, 1] - 1.0) > 1e-10:
            raise ValueError("intervals must cover [-1,1]")
        if np.any(self.intervals[:, 0] >= self.intervals[:, 1]) or np.any(
            np.abs(self.intervals[:-1, 1] - self.intervals[1:, 0]) > 1e-10
        ):
            raise ValueError("intervals must be contiguous and increasing")
        self.n_lambdas = 4 * L
        self.n_vars = 1 + self.n_lambdas
        self.A = self._build_matrix()

    def idx(self, bucket: int, tau: int, kind: int) -> int:
        # kind: 0 lower, 1 upper
        return 1 + ((bucket * 2 + tau) * 2 + kind)

    def _add_endpoint(
        self,
        rows: list[int],
        cols: list[int],
        data: list[float],
        row: int,
        sign: int,
        bucket: int,
        tau: int,
        weight: float,
    ) -> None:
        ell = float(self.intervals[bucket, 0])
        rr = float(self.intervals[bucket, 1])
        A = weight if sign == 0 else -weight
        D = weight
        # LP rows are rho*o - sum(lambda*g) <= r.
        rows.append(row)
        cols.append(self.idx(bucket, tau, 0))
        data.append(-(-A + ell * D))
        rows.append(row)
        cols.append(self.idx(bucket, tau, 1))
        data.append(-(A - rr * D))

    def _build_matrix(self) -> csr_matrix:
        L = self.L
        rows: list[int] = []
        cols: list[int] = []
        data: list[float] = []
        row = 0

        for sign, bucket, tau in product((0, 1), range(L), (0, 1)):
            rows.append(row)
            cols.append(0)
            data.append(1.0 if lit_sat(sign, tau) else 0.0)
            self._add_endpoint(rows, cols, data, row, sign, bucket, tau, self.unary_endpoint_weight)
            row += 1

        for a, b in product((0, 1), (0, 1)):
            for i, j in product(range(L), range(L)):
                for tau, ups in product((0, 1), (0, 1)):
                    rows.append(row)
                    cols.append(0)
                    data.append(1.0 if (lit_sat(a, tau) or lit_sat(b, ups)) else 0.0)
                    self._add_endpoint(rows, cols, data, row, a, i, tau, 0.5)
                    self._add_endpoint(rows, cols, data, row, b, j, ups, 0.5)
                    row += 1

        return coo_matrix((data, (rows, cols)), shape=(row, self.n_vars)).tocsr()

    def rhs(self, p: np.ndarray) -> np.ndarray:
        L = self.L
        p = np.asarray(p, dtype=float)
        rhs = np.empty(4 * L + 16 * L * L, dtype=float)
        row = 0

        def q(sign: int, bucket: int) -> float:
            return float(p[bucket] if sign == 0 else 1.0 - p[bucket])

        for sign, bucket, _tau in product((0, 1), range(L), (0, 1)):
            rhs[row] = q(sign, bucket)
            row += 1

        for a, b in product((0, 1), (0, 1)):
            for i, j in product(range(L), range(L)):
                qa = q(a, i)
                qb = q(b, j)
                r = 1.0 - (1.0 - qa) * (1.0 - qb)
                for _tau, _ups in product((0, 1), (0, 1)):
                    rhs[row] = r
                    row += 1
        return rhs

    def solve(self, p: np.ndarray) -> SolveResult:
        p = np.asarray(p, dtype=float)
        rhs = self.rhs(p)
        c = np.zeros(self.n_vars, dtype=float)
        c[0] = -1.0
        bounds = [(0.0, 1.0)] + [(0.0, None)] * self.n_lambdas
        res = linprog(c, A_ub=self.A, b_ub=rhs, bounds=bounds, method="highs")
        if not res.success:
            return SolveResult(
                self.L,
                self.unary_weight,
                0.0,
                0.0,
                -1,
                p,
                np.zeros(self.n_lambdas),
                self.intervals,
                False,
                res.message,
            )
        slacks = rhs - self.A.dot(res.x)
        min_row = int(np.argmin(slacks))
        return SolveResult(
            self.L,
            self.unary_weight,
            float(res.x[0]),
            float(slacks[min_row]),
            min_row,
            p,
            np.asarray(res.x[1:], dtype=float),
            self.intervals,
            True,
            res.message,
        )


def load_p(path: str | None, L: int, intervals: np.ndarray | None = None) -> np.ndarray:
    if path is None:
        if intervals is None:
            return interpolate_p(P24, L)
        return interpolate_p_at(P24, interval_centers(intervals))
    data = json.loads(Path(path).read_text())
    if isinstance(data, dict):
        p = np.array(data["p"], dtype=float)
        source_intervals = np.asarray(data.get("intervals", uniform_intervals(len(p))), dtype=float)
    else:
        p = np.array(data, dtype=float)
        source_intervals = uniform_intervals(len(p))
    if intervals is not None:
        if len(p) == L and np.max(np.abs(source_intervals - intervals)) < 1e-10:
            return symmetrize_monotone(p)
        return interpolate_p_between_intervals(p, source_intervals, intervals)
    if len(p) == L:
        return symmetrize_monotone(p)
    return interpolate_p(p, L)


def load_intervals(args: argparse.Namespace) -> np.ndarray:
    if getattr(args, "intervals_json", None):
        data = json.loads(Path(args.intervals_json).read_text())
        if isinstance(data, dict):
            data = data["intervals"]
        return np.asarray(data, dtype=float)
    components = list(getattr(args, "focus_component", None) or [])
    if components:
        if getattr(args, "focus", None) is not None:
            components.insert(0, (args.focus, args.focus_strength, args.focus_sigma))
        return make_multi_focus_intervals(args.L, components)
    if getattr(args, "power", None) is not None:
        return make_power_intervals(args.L, args.power)
    if getattr(args, "focus", None) is not None:
        return make_focus_intervals(args.L, args.focus, args.focus_strength, args.focus_sigma)
    return uniform_intervals(args.L)


def load_p_for_intervals(args: argparse.Namespace, intervals: np.ndarray) -> np.ndarray:
    if args.p_json is not None:
        return load_p(args.p_json, args.L, intervals)
    return interpolate_p_at(P24, interval_centers(intervals))


def parse_weights(values: list[str]) -> list[float]:
    out: list[float] = []
    for value in values:
        if ":" in value:
            start, stop, step = map(float, value.split(":"))
            n = int(np.floor((stop - start) / step + 1e-9)) + 1
            out.extend(float(start + i * step) for i in range(n + 1) if start + i * step <= stop + 1e-9)
        else:
            out.append(float(value))
    return out


def cmd_eval(args: argparse.Namespace) -> None:
    intervals = load_intervals(args)
    p = load_p_for_intervals(args, intervals)
    model = SparseCertificateModel(args.L, args.unary_weight, intervals)
    result = model.solve(p)
    print_result(result)
    maybe_write(args.output_json, result)


def cmd_sweep(args: argparse.Namespace) -> None:
    intervals = load_intervals(args)
    p = load_p_for_intervals(args, intervals)
    results = []
    for w in parse_weights(args.weights):
        model = SparseCertificateModel(args.L, w, intervals)
        result = model.solve(p)
        results.append(result)
        print(f"w={w:.6g} rho={result.rho:.12f} min_slack={result.min_slack:.3e} min_row={result.min_row}", flush=True)
    if args.output_json:
        Path(args.output_json).write_text(json.dumps([r.as_jsonable() for r in results], indent=2))
    best = max(results, key=lambda r: r.rho)
    print("BEST")
    print_result(best)


def cmd_search(args: argparse.Namespace) -> None:
    intervals = load_intervals(args)
    base = load_p_for_intervals(args, intervals)
    model = SparseCertificateModel(args.L, args.unary_weight, intervals)
    h = args.L // 2
    base_half = np.asarray(base[:h], dtype=float)
    rng = np.random.default_rng(args.seed)
    init = [base_half]
    for scale in args.init_scales:
        for _ in range(args.init_copies):
            init.append(np.clip(base_half + rng.normal(0.0, scale, h), 0.0, 0.5))
    init_arr = np.asarray(init, dtype=float)
    min_pop = 5 * h
    if len(init_arr) < min_pop:
        extra = rng.random((min_pop - len(init_arr), h)) * 0.5
        init_arr = np.vstack([init_arr, extra])

    best: SolveResult | None = None
    cache: dict[tuple[float, ...], float] = {}

    def objective(x: np.ndarray) -> float:
        nonlocal best
        p = symmetric_from_half(x, args.L)
        key = tuple(np.round(p, 12))
        if key in cache:
            return cache[key]
        result = model.solve(p)
        value = -result.rho if result.success else 1.0
        cache[key] = value
        if result.success and (best is None or result.rho > best.rho):
            best = result
            print(
                f"new best L={args.L} w={args.unary_weight:.6g} "
                f"rho={result.rho:.12f} min={result.min_slack:.2e} "
                f"p={format_probs(result.p)}",
                flush=True,
            )
            maybe_write(args.output_json, result)
        return value

    differential_evolution(
        objective,
        bounds=[(0.0, 0.5)] * h,
        init=init_arr,
        maxiter=args.maxiter,
        popsize=args.popsize,
        seed=args.seed,
        polish=args.polish,
        updating="immediate",
        workers=1,
        tol=1e-8,
        atol=1e-9,
    )

    if best is None:
        raise SystemExit("search failed to find a feasible candidate")
    print("BEST")
    print_result(best)
    maybe_write(args.output_json, best)


def maybe_write(path: str | None, result: SolveResult) -> None:
    if not path:
        return
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result.as_jsonable(), indent=2))


def print_result(result: SolveResult) -> None:
    print("success:", result.success, result.message)
    print(f"L = {result.L}")
    print(f"unary_weight = {result.unary_weight:.15g}")
    print(f"rho = {result.rho:.15f}")
    print(f"min_slack = {result.min_slack:.3e} at row {result.min_row}")
    print("p =", format_probs(result.p))
    widths = result.intervals[:, 1] - result.intervals[:, 0]
    print(f"bucket_widths: min={widths.min():.6g} max={widths.max():.6g}")


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--L", type=int, required=True)
    common.add_argument("--p-json", default=None, help="JSON file containing p or a previous result object")
    common.add_argument("--intervals-json", default=None, help="JSON file containing custom intervals")
    common.add_argument("--power", type=float, default=None, help="symmetric power-warp interval exponent")
    common.add_argument("--focus", type=float, default=None, help="focus extra density around +/-focus")
    common.add_argument("--focus-strength", type=float, default=2.0)
    common.add_argument("--focus-sigma", type=float, default=0.05)
    common.add_argument(
        "--focus-component",
        action="append",
        type=parse_focus_component,
        default=None,
        help="additional density component focus:strength:sigma; may be repeated",
    )

    p_eval = sub.add_parser("eval", parents=[common])
    p_eval.add_argument("--unary-weight", type=float, required=True)
    p_eval.add_argument("--output-json", default=None)
    p_eval.set_defaults(func=cmd_eval)

    p_sweep = sub.add_parser("sweep", parents=[common])
    p_sweep.add_argument("--weights", nargs="+", required=True, help="weights or ranges start:stop:step")
    p_sweep.add_argument("--output-json", default=None)
    p_sweep.set_defaults(func=cmd_sweep)

    p_search = sub.add_parser("search", parents=[common])
    p_search.add_argument("--unary-weight", type=float, required=True)
    p_search.add_argument("--maxiter", type=int, default=20)
    p_search.add_argument("--popsize", type=int, default=8)
    p_search.add_argument("--seed", type=int, default=0)
    p_search.add_argument("--init-scales", nargs="*", type=float, default=[0.003, 0.01, 0.03])
    p_search.add_argument("--init-copies", type=int, default=8)
    p_search.add_argument("--polish", action="store_true")
    p_search.add_argument("--output-json", default=None)
    p_search.set_defaults(func=cmd_search)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
